### ISSUE TITLE
API Deprecated 

### ISSUE THREAD

**Issue by chrishough** [timraymond/pricegrabber#2]
I just came across https://www.programmableweb.com/api/pricegrabber and was curious if this has been formally confirmed?

**Comment by timraymond** [comment]
@chrishough Interesting—it's the first I've heard of it. I haven't used their API (and, consequently, this gem) in ages, but I'll reach out to a friend who may still be actively using it to check if they can confirm.

**Comment by timraymond** [comment]
@chrishough My contact says that the API is dead, unfortunately, and has been for some time 🙁 Sorry I couldn't be of more help. Thanks for bringing this to my attention though! I'll stick a notice on the README.

**Comment by chrishough** [comment]
Thank you for reaching out to your contact. I appreciate it. Have a great weekend.
